### ISSUE TITLE
Portal authentication

### ISSUE THREAD

**Issue by jbecker01** [USSF-ORBIT/ussf-portal-client#136]
Introduction:

This feature will allow users to login and access content on the USSF portal.  In addition, the system will make a request for user information to be used in personalizing the experience for the service member. 

Product Requirements:
A user can:
- see a login screen
- be prompted to enter their CAC
- select their certificate
- enter their pin
- successfully login to the USSF portal
- see the portal home page

The system can:
- TBD

Technical Requirements:
- Akamai notes: https://docs.google.com/document/d/1FMa5YaHpV2GfC1ih0ouM_fSS5c2pBNrYfGSzMpPV2t8/edit?usp=sharing

Design requirement:
- TBD

**Comment by jbecker01** [comment]
- [ ] https://github.com/USSF-ORBIT/ussf-portal-client/issues/281
- [ ] https://github.com/USSF-ORBIT/ussf-portal-client/issues/87
- [ ] https://github.com/USSF-ORBIT/ussf-portal-client/issues/126
- [ ] https://github.com/USSF-ORBIT/ussf-portal-client/issues/127
- [ ] https://github.com/USSF-ORBIT/ussf-portal-client/issues/128
