### ISSUE TITLE
Sites & Application fixes for static prototype testing

### ISSUE THREAD

**Issue by suzubara** [USSF-ORBIT/ussf-portal-client#286]
Use this issue to log minor UX/UI tweaks we want to fix _before_ using the static site prototype in interviews with users.

**Deferred:**
- [ ] ~Add save/cancel buttons when editing a collection title~ (determine if needed)

**Covered in other issues:**
- [ ] Unable to close fly-out menu (https://github.com/USSF-ORBIT/ussf-portal-client/issues/282)
- [ ] Fill in missing URLs & descriptions on Sites & Applications page (https://github.com/USSF-ORBIT/ussf-portal-client/issues/287)
- [ ] Add Link URL validation (https://github.com/USSF-ORBIT/ussf-portal-client/issues/270)

**COMPLETE:**
- [x] Adjust MySpace columns to 3, maybe adjust margins/padding
- [x] Change color on search dropdown text to white 
- [x] Change padding on collections boxes (24px for top/bottom and 16pc for L/R)
- [x] Even out padding within myspace container (24px on all sides)
- [x] Remove side nav links that are unused (My profile, Subordinate profiles, etc...)
- [x] Change all footer text to white
- [x] Add hover states to buttons - @malworks 
- [x] Remove hover state for search dropdown
- [x] "Add section" box height should be equal to a collection card with 5 links inside it
- [x] "Search" text is not using trebuchet - @malworks 
- [x] In "alphabetical" view, description columns will need to be moved to the left to make room for more content (Note: this might actually be resolved on it's own once content is added)
- [x] Add hover states to main nav - @malworks 
- [x] Update button styles on alphabetical/type sorts @malworks / @suzubara 
- [x] ReactUSWDS ComboBox scroll bug (https://github.com/trussworks/react-uswds/issues/1693)
