### ISSUE TITLE
Visual branding implementation

### ISSUE THREAD

**Issue by suzubara** [USSF-ORBIT/ussf-portal-client#368]
Checklist:
- [x] Adding our typeface (from gdrive Branding folder) - #372 
- [x] Add typography Storybook examples & styles - #372 
- [x] Add custom colors for links - #372 
- [x] Add custom colors for buttons - #372 
- [ ] Background image for the header (need asset) - #374 
- [ ] Update side nav to match Figma - #374 

Soft launch:
- [x] Blur out Search - #374 
- [ ] #378
- [ ] Hide Header links - track in #378
- [ ] Footer links? - add external URLs, hide Help & Support - track in #377
- [x] Final CMS content - #366
