### ISSUE TITLE
Add tracking events

### ISSUE THREAD

**Issue by suzubara** [USSF-ORBIT/ussf-portal-client#471]
We would also like to capture event actions on a page using trackEvent on the following buttons:

My Space page:
- [ ] Add link 
- [ ] Add section 
- [ ] Create new collection
- [ ] Select from template

All sites & applications:
- [ ] Add to My Space
- [ ] Example collections
- [ ] Add to new collection
- [ ] Sort alphabetically
- [ ] Sort by type
- [ ] Select multiple collections

**Comment by suzubara** [comment]
Moving to blocked, needs tracking specs for each event (preferably in a spreadsheet) @jbecker01
